### ISSUE TITLE
segfault on delete loop

### ISSUE THREAD

**Issue by bill-auger** [bill-auger/loopidity#10]

**Comment by bill-auger** [comment]
the Trace class has had quite a bit of attention since this issue was posted - this bug may well be squished

**Comment by arnaudfi** [comment]
Hello,

I am a librazik user / tester , and I have tested your software, my report is here : http://librazik.tuxfamily.org/flyspray/index.php?do=details&task_id=1080  but it is in french...

I try a translation : when I record a first loop (press space, playing guitar, press space again) and wait more than 1 loop and press ESC then the software crush. Here is the message in the terminal  

Trace::TraceState(): 'Scene::deleteLoop(0)     IN' bool0=1 bool1=1bool2=1
ERROR: Scene::deleteLoop(0)     IN   111    MODEL: Scene::mvc inconsistent
Trace::TraceState(): Event(36)='ERROR: Scene::deleteLoop(0)     IN  '
Trace::TraceState(): State(6)='111   '
Trace::TraceState(): Desc(30)='MODEL: Scene::mvc inconsistent'
Trace::TraceState(): 'Scene::deleteLoop(0)     IN' bool0=1 bool1=1bool2=1
ERROR: Scene::deleteLoop(0)     IN      111 VIEW:  SceneSdl::mvc inconsistent
Trace::TraceState(): Event(36)='ERROR: Scene::deleteLoop(0)     IN  '
Trace::TraceState(): State(6)='   111'
Trace::TraceState(): Desc(33)='VIEW:  SceneSdl::mvc inconsistent'

If I press ESC before the end of the second loop, no problem...

As a french, I am using a AZERTY PC keyboard : I had some issues with freewheeling because of that, so maybe it is connected... 

Hope this could be useful for you ! Your software seem nice :)

Bye

Fidz

**Comment by bill-auger** [comment]
confirmed

```
KEY: SDLK_ESCAPE

USER: SDLK_ESCAPE --> Loopidity::DeleteLastLoop(0)

MODEL: Loopidity::DeleteLastLoop(0)  111    isRecording=1 shouldSaveLoop=1 doesPulseExist=1
VIEW:  Loopidity::DeleteLastLoop(0)     111 nLoops=1 nHistogramImgs=1 nLoopImgs=1


USER: SDL_BUTTON_MIDDLE --> Loopidity::DeleteLoop(0)

MODEL: Loopidity::DeleteLoop(0)  IN  111    isRecording=1 shouldSaveLoop=1 doesPulseExist=1
VIEW:  Loopidity::DeleteLoop(0)  IN     111 nLoops=1 nHistogramImgs=1 nLoopImgs=1

ERROR: Scene::deleteLoop(0)     IN   111    MODEL: Scene::mvc inconsistent
ERROR: Scene::deleteLoop(0)     IN      111 VIEW:  SceneSdl::mvc inconsistent

ERROR: Loopidity::DeleteLoop(0) OUT  111    MODEL: Scene::mvc inconsistent
ERROR: Loopidity::DeleteLoop(0) OUT     111 VIEW:  SceneSdl::mvc inconsistent

ERROR: Loopidity::DeleteLoop(0) OUT  111    MODEL: Scene::mvc inconsistent
ERROR: Loopidity::DeleteLoop(0) OUT     111 VIEW:  SceneSdl::mvc inconsistent


Thread 1 "loopidity" received signal SIGSEGV, Segmentation fault.
....
(gdb) bt
#0  SceneSdl::drawScene (this=<optimized out>, surface=<optimized out>, currentPeakN=<optimized out>, sceneProgress=<optimized out>) at scene_sdl.cpp:251
#1  0x000055555555b0aa in LoopiditySdl::DrawScenes (currentSceneN=<optimized out>, nextSceneN=0 '\000') at loopidity_sdl.cpp:260
#2  0x000055555555aa99 in Loopidity::Main (argc=<optimized out>, argv=<optimized out>) at loopidity.cpp:133
#3  0x00007ffff7819b25 in __libc_start_main () from /usr/lib/libc.so.6
#4  0x0000555555557dce in _start ()
```

**Comment by bill-auger** [comment]
i noticed that the bug was not present with logging disabled - this was caused by return statements in the pre-processor logging defines (a naughty design flaw) - those are gone now, and the program no longer segfaults for that reason (this ticket is technically 'fixed') - though it could use some more testing, to ensure that this did not cause a regression

**Comment by trebmuh** [comment]
hi @bill-auger 
Do you mean that I just need to rebuild from git master for this bug to be gone?

**Comment by bill-auger** [comment]
that could be, but the master branch is much older code than the version in librazik now - this is a good opportunity to promote the development branch - i have not pushed the fix for this ticket yet - the VCS just needs some cleanup first

if you hoping to meet a deadline, let me know - i will prioritize it if necessary
